name: Build
on: [push, pull_request]

jobs:
  Build:
    name: "Build on ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            runtime: linux-x64
            name: Linux
          - os: windows-latest
            runtime: win-x64
            name: Windows
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install Xorg lib
        if: matrix.name == 'Linux'
        run: |
            sudo apt install -y libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build .
      - name: CheckBinaryName
        shell: bash
        if: matrix.name == 'Linux'
        run: test -f build/bomberman