name: Check coding style
on: [push]

jobs:
  Building:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Install cpplint
        run: pip install cpplint
      - name: Check coding style
        run: |
          cpplint --recursive --quiet --verbose=3 . 2> tmp
      - name: Comment PR
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: thollander/actions-comment-pull-request@master
        with:
          message: ${{ github.event_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}