name: Check coding style
on: [push, pull_request]

jobs:
  Building:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Install cpplint
        run: pip install cpplint
      - name: Check coding style
        run: |
          cpplint --recursive --quiet --verbose=3 . 2> tmp
          cat tmp
          ls >> tmp
          echo "CPP_LINT_LOG=$(cat tmp)" >> $GITHUB_ENV
      - name: Comment PR
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: thollander/actions-comment-pull-request@master
        with:
          message: ${{ env.CPP_LINT_LOG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}