name: Check coding style
on: [push, pull_request]

jobs:
  Building:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@1.0.1
        with:
          message: '${{ cat tmp }}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}