name: Check coding style
on: [push, pull_request]

jobs:
  Building:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Install cpplint
        run: pip install cpplint
      - name: Check coding style
        run: |
          cpplint --recursive --quiet --verbose=3 .
      - name: Comment PR
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@master
        with:
          message: '${{ cat tmp }}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}