name: Check coding style
on: [push]

jobs:
  Building:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Install cpplint
        run: pip install cpplint
      - name: Check coding style
        run: |
          cpplint --recursive --quiet --verbose=3 . 2> tmp
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message:  ${{ cat tmp }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}