name: Web Building
on:
  push:
    branches:
      wasm

jobs:
  Push:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        ref: master
    - name: Exec
      shell: bash
      run: |
        PRJECTDIR=`pwd`
        git clone https://github.com/emscripten-core/emsdk.git
        EMSDK_PATH=$PRJECTDIR/emsdk
        cd $EMSDK_PATH &&
        ./emsdk install tot &&
        ./emsdk install latest && 
        ./emsdk activate latest && 
        source ./emsdk_env.sh &&
        EMSCRIPTEN_PATH=$EMSDK_PATH/upstream/emscripten
        CLANG_PATH=$EMSDK_PATH/upstream/bin
        PATH=$PATH:$EMSDK_PATH:$EMSCRIPTEN_PATH:$CLANG_PATH:$NODE_PATH &&
        cd $PRJECTDIR &&
        emcmake cmake -S . -B build &&
        make PLATFORM=PLATFORM_WEB -B &&
        cmake --build build && 
        make -C build PLATFORM=PLATFORM_WEB -B &&
        python3 wasm-server.py