name: Web Building
on:
  push:
    branches:
      wasm

jobs:
  Push:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        ref: master
    - name: Exec
      shell: bash
      run: ./emsdk.sh
    - name: Check files creation
      run: |
        test -f build/bomberman.html
        test -f build/bomberman.js
        test -f build/bomberman.wasm 
        test -f build/bomberman.data
